LINKEDIN_RECOMMENDED_JOB_URL = "https://www.linkedin.com/jobs/collections/recommended"
CHROME_EXE_PATH = "C:/Selenium/Profiles/B_Automation"
PROFILE="Default"

#TIMOUTS
TIMEOUT_BEFORE_DATA_SCRAPING = 20
TIMEOUT_AFTER_DATA_SCRAPING= 1

SLEEP_TIME_AFTER_DIRECT_TO_JOBS = 10
JOB_PAGE_RENDERING_TIME = 15
JOB_PAGE_ELEMENTS_RENDERING_TIME = 60
DATA_SCRAPING_TIME = 0.15
FETCHING_DATA_TIME = 0.6

ITEM_COUNTS_PER_SCROLL = 5