JOB_ID = "data-occludable-job-id"
JOB_TITLE = "job-card-list__title--link"
COMPANY = "artdeco-entity-lockup__subtitle"
COMPANY_LOCATION = "job-card-container__metadata-wrapper"
GLOBAL_NAVBAR = "global-nav"
GLOBAL_NAV_SEARCH = "global-nav-search"
VISIBLE_COUNT_IN_LIST = "li[data-occludable-job-id], li[id^='ember']"
ITEMS_IN_LIST = "li[data-occludable-job-id], li[id^='ember']"
SCROLL_ITEMS = "//div[@data-results-list-top-scroll-sentinel]/following-sibling::ul[1]"