name: Run main.py

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      DB_USER_CLOUD: ${{ secrets.DB_USER_CLOUD }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_DSN: ${{ secrets.DB_DSN }}
      DB_WALLET_DIR: ${{ secrets.DB_WALLET_DIR }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Set environment variables
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_DSN=${{ secrets.DB_DSN }}" >> $GITHUB_ENV
      - name: Check database connectivity
        run: |
          echo "Pinging database host..."
          ping -c 4 adb.ap-mumbai-1.oraclecloud.com
          echo "Testing database port..."
          nc -zv adb.ap-mumbai-1.oraclecloud.com 1522
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run main.py
        run: python main.py